server:
  port: 50000

spring:
  application:
    name: board-comment-service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@octocat.c21x4yygth5e.us-east-2.rds.amazonaws.com:1521:ORCL
    username: p3boardcomment
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://13.59.67.21:8761/eureka/

security:
 oauth2:
   resource:
     accessTokenUri: http://13.59.67.21:8765/user-service/oauth/check_token
     userAuthorizationUri: http://13.59.67.21:8765/user-service/oauth/authorize
     jwt:
       keyUri: http://13.59.67.21:8765/user-service/oauth/token_key
