server:
  port: 50000

spring:
  application:
    name: board-comment-service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@octocat.c21x4yygth5e.us-east-2.rds.amazonaws.com:1521:ORCL
    username: p3boardcomment
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: ${DOCKER_HOST_IP}:${server.port}
#    serviceUrl:
#      defaultZone: http://18.221.160.13:8761/eureka
