server:
  port: 8762
  
spring:
  application:
    name: Eureka-Service
  datasource:
    tomcat: 
      initial-size: 1
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
