server:
  port: 50003

spring:
  application:
    name: story-manager-service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@octocat.c21x4yygth5e.us-east-2.rds.amazonaws.com:1521:ORCL
    username: p3story
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
#  cloud:
#    stream:
#      bindings:
#        output:
#          contentType: application/json
#  integration:
#    readOnly:
#      headers: contentType
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
#    serviceUrl:
#      defaultZone: http://18.221.160.13:8761/eureka
