server:
  port: 0

spring:
  application:
    name: Story-Service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@octocat.c21x4yygth5e.us-east-2.rds.amazonaws.com:1521:ORCL
    username: ocatest
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
