server:
  port: 50005

spring:
  application:
    name: user-service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@octocat.c21x4yygth5e.us-east-2.rds.amazonaws.com:1521:ORCL
    username: p3user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://13.59.67.21:8761/eureka/
#      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}
#    hostname: ${DOCKER_HOST_IP}:${server.port}
