server:
  port: 8765

spring:
  application:
    name: Zuul-Service
  datasource:
    tomcat: 
      initial-size: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.221.160.13:8761/eureka
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
