server:
  port: 8765

spring:
  application:
    name: Zuul-Service
  datasource:
    tomcat: 
      initial-size: 1
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://13.59.67.21:8761/eureka
      
zuul:
  ignoredHeaders: - authorization
  ignored-services: "*"
  routes:
    userservice:
      path: /user-service/**
      sensitiveHeaders:
      serviceId: user-service
    storyservice:
      path: /story-manager-service/**
      sensitiveHeaders:
      serviceId: story-manager-service
    baordservice:
      path: /board-manager-service/**
      sensitiveHeaders:
      serviceId: board-manager-service
    taskservice:
      path: /task-manager-service/**
      sensitiveHeaders:
      serviceId: task-manager-service
    chartservice:
      path: /chart-service/**
      sensitiveHeaders:
      serviceId: chart-service
    boardcommentservice:
      path: /board-comment-service/**
      sensitiveHeaders:
      serviceId: board-comment-service
    route:
      path: /routes/**
      sensitiveHeaders:
      serviceId: Zuul-Service
