server:
  port: 8765

spring:
  application:
    name: Zuul-Service
  datasource:
    tomcat: 
      initial-size: 1
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka
